server:
  port: 8082

logging:
  level:
    top.w2gd.content.openfeign.UserService: debug

jwt:
  secret: aaaaaaaaaabbbbbbbbbbbcccccccccccddddddd
  # 有效期
  expire-time-in-second: 1209600

rocketmq:
  name-server: 124.221.138.97:9876
  producer:
    # 必须指定 group
    group: test-group